### PR TITLE
Added PyInquirer based UI to -i option

### PR DESCRIPTION
**Pull request by FarazzShaikh**
# Added PyInquirer based UI

Screen Recording 2021-01-18 at 1 17 05 PM

Made the `-i` options more user friendly.

Minor changes:
- Changed the Event Designator `!#` from `#!/usr/bin/python3` -> `#!/usr/bin/env python3`. See advantages [here](https://stackoverflow.com/questions/16365130/what-is-the-difference-between-usr-bin-env-bash-and-usr-bin-bash/#:\~:text\=Using%20%23!%2Fusr%2Fbin%2Fenv,want%20to%20search%20for%20it.\&text\=If%20the%20shell%20scripts%20start,run%20with%20bash%20from%20%2Fbin%20).

### CODE REVIEW

**Comment by FarazzShaikh** [comment]
@PC-02 I mentioned I would add this on LinkedIn, please review.

**Comment by Akilan1999** [comment]
It's approved from my side. Just need @PC-02 to review it too.

**Comment by PC-02** [comment]
Doesn't seem to be displaying any of the outputs, neither error messages nor scan results. @Akilan1999 & @lolmokha take a look?

**Comment by PC-02** [comment]
Doesn't seem to be displaying any of the outputs, neither error messages nor scan results. @Akilan1999 & @lolmokha take a look?

**Comment by FarazzShaikh** [comment]
I don't have API keys, so functionality is untested. But it should work because nothing is changed other than the UI. @PC-02 that's weird can you at least get the UI to work? Does it exit after you select an option?l or go into in infinite loop?

**Comment by Akilan1999** [comment]
I will pull the PR and test run it to confirm

**Comment by PC-02** [comment]
> I don't have API keys, so functionality is untested. But it should work because nothing is changed other than the UI. @PC-02 that's weird can you at least get the UI to work? Does it exit after you select an option?l or go into in infinite loop?

think its an issue with how the UI handles the printed output, tested a site out with a flag and got the expected output, did the same with the UI and instead of showing me any output took me directly back to the main menu

**Comment by FarazzShaikh** [comment]
> think its an issue with how the UI handles the printed output, tested a site out with a flag and got the expected output, did the same with the UI and instead of showing me any output took me directly back to the main menu

I took A quick look at the code. There is a `continue` after each case, after the output is printed the whole loop runs again, clearing the console and starting the menu again. Maybe replace the continue with `break` and it should work? If you are on your computer right now try it out, if it works I'll make the change real quick.

**Comment by PC-02** [comment]
> `nue` after each case, after the outp

that does fix the interactive code, but do you think there would be any way to implement it such that we can use continue, for the interactive menu in earlier discussions it made more sense to keep the user in the interactive menu until they leave, maybe an implementation where the user can see the output, scroll through it and press and key to get back to the main menu. Would something like that be feasible?

**Comment by FarazzShaikh** [comment]
> do you think there would be any way to implement it such that we can use continue

Yep of course, just clear the console and print the logo before printing the results. I'll make the changes and add it to the PR.

**Comment by FarazzShaikh** [comment]
@PC-02 See if it works the way you want it now after e7c9b27.

**Review by PC-02 — APPROVED** [review]
Everything looks good now, thank you!

**Pull request merged**
